config/routes.rb
Rails.application.routes.draw do
  resources :tags
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :boards do
    resources :tags 
    resources :sounds do 
	    resources :comments
    end
  end
  resources :users do
    resources :comments
  end
  resources :users do
    resources :sounds
  end
  root "boards#index"
end

app/models/board.rb
class Board < ApplicationRecord
  validates :name, presence: true
  has_many :sounds, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    if params[:search] != nil && params[:search] != ""
      @boards = Board.joins(:tags).where("tags.name" => params[:search]).paginate(:per_page => 10, :page => params[:page]).order("created_at DESC")
    else
      @boards = Board.paginate(:per_page => 10, :page => params[:page]).order("created_at DESC")
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
      @sounds = @board.sounds.paginate(:per_page => 10, :page => params[:page]).order("created_at DESC")
      @tags = @board.tags.paginate :per_page => 10, :page => params[:page]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :description, :color)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sound-container">
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 right-content">
      	<%= link_to board_path(board) do %><h4 class = "sound-name"><%= board.name %></h4><% end %>
      	<p><%= board.description %></p>
      	<% if board.tags.count > 0 %>
      		<div>
	      		<span>Tags: </span>
		      	<% board.tags.each do |tag| %>
		          <span>#<%=tag.name %> </span>
		        <% end %>
	        </div>
        <% end %>
      	<%= link_to board_path(board), class: 'sound-bottom-link' do %><p><%= pluralize(board.sounds.count, "sound") %></p><% end %>
      	<a onclick = "handleShareClick('<%= board.id %>')" class = "sound-bottom-link">Share</a>
        <div id = "share-<%= board.id %>" class = "share">
          <a class = "share-button" href = "https://www.facebook.com/sharer/sharer.php?u=<%= board_url(board) %>"><%= image_tag "facebook.png" %></a>
          <a class = "share-button" href = "https://twitter.com/home?status=<%= board_url(board) %>"><%= image_tag "twitter.png" %></a>
          <a class = "share-button" href = "https://plus.google.com/share?url=<%= board_url(board) %>"><%= image_tag "google_plus.png" %></a>
          <a class = "share-button" href = "https://www.linkedin.com/shareArticle?mini=true&url=<%= board_url(board) %>&title=Check%20out%20this%20sound%20board&summary=&source="><%= image_tag "linkedin.png" %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/_form.html.erb
<div id = "board-info" class = "form">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 board-info-container">
      <div class = "blank-info"></div>
        <%= form_for(board) do |f| %>
          <div class = "add-info">
            <% if board.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

                <ul>
                <% board.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="field">
              <%= f.text_field :name, placeholder: "Board name" %>
            </div>

            <div class="field">
              <%= f.text_field :description, placeholder: "Board description" %>
            </div>

            <div class="field">
              <%= f.color_field :color %>
            </div>

            <div class="actions">
              <%= f.submit 'Submit board', :class => 'sidebar-buttons' %>
            </div>
          </div>
        <% end %> 
        <div class = "edit-info">
          <%= link_to 'Show this board', @board, :class => 'sidebar-buttons back-button' %>
          <%= link_to 'Back to home', boards_path, :class => 'sidebar-buttons' %>
        </div>
    </div>
  </div>
</div>

app/views/boards/_sound.html.erb
<div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sound-container">
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-1 col-md-2 col-sm-1 col-xs-1 left-content">
        <i class = "fa fa-play-circle-o" id = "sound-play-pause-<%= sound.id %>" aria-hidden = "true" onClick="handleAudioImageClick('<%= sound.id %>')"></i>
      </div>
      <div class = "col-lg-11 col-md-11 col-sm-11 col-xs-11 right-content">
        <%= link_to board_sound_path(@board, sound) do %><h4 class = "sound-name"><%= sound.name %></h4><% end %>

        <audio loop id = "<%= sound.id %>-audio">
          <source src = "<%= sound.soundAttachment.url %>" type = "audio/mp3">
        </audio>

	<p>Submitted <%= time_ago_in_words(sound.created_at) %> ago by <%= link_to User.find(sound.user_id).name, User.find(sound.user_id) %></p>

        <%= link_to board_sound_path(@board, sound), class: 'sound-bottom-link'  do %><p><%= sound.comments.count %> <%= "comment".pluralize(sound.comments.count) %></p><% end %>
        <%= link_to 'Delete', board_sound_path(@board, sound), data: { confirm: 'Are you sure?' }, method: :delete,  class: 'sound-bottom-link' %>
        <%= link_to 'Download', sound.soundAttachment.url, class: 'sound-bottom-link' %>
        <a onclick = "handleShareClick('<%= sound.id %>')" class = "sound-bottom-link">Share</a>
        <div id = "share-<%= sound.id %>" class = "share">
          <a class = "share-button" href = "https://www.facebook.com/sharer/sharer.php?u=<%= board_sound_url(@board, sound) %>"><%= image_tag "facebook.png" %></a>
          <a class = "share-button" href = "https://twitter.com/home?status=<%= board_sound_url(@board, sound) %>"><%= image_tag "twitter.png" %></a>
          <a class = "share-button" href = "https://plus.google.com/share?url=<%= board_sound_url(@board, sound) %>"><%= image_tag "google_plus.png" %></a>
          <a class = "share-button" href = "https://www.linkedin.com/shareArticle?mini=true&url=<%= board_sound_url(@board, sound) %>&title=Check%20out%20this%20sound&summary=&source="><%= image_tag "linkedin.png" %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/edit.html.erb
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<div id = "board-sounds">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sounds-header">
      <h3>SoundShare</h3>
      <div class = "description">

      </div>
    </div>
    <% if @boards.count > 0 %>
       <%= will_paginate @boards, :class => 'pagination first' %>
       <% @boards.each do |board| %>
    			<%= render 'board', board: board %>
  			<% end %>
      <%= will_paginate @sounds %>
    <% else %>
		  <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12">
		    <p id = "empty-content-message">There doesn't seem to be anything here! Be first first to create a new board.</p>
		  </div>
		<% end %>
	</div>
</div>


<div id = "board-info">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 board-info-container">
      <div class = "blank-info">
      </div>
      <div class = "add-info searchbar">
        <h4>Search by tags</h4>
        <%= form_tag boards_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search], placeholder: 'Search' %>
          <%= submit_tag "Search", :name => nil, class: 'sidebar-buttons' %>
        <% end %>
      </div>
      <% if logged_in? %>	    
      <div class = "add-info">
        <h4>Submit a new board</h4>
        <%= form_for Board.new do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: "Board name" %>
          </div>

          <div class="field">
            <%= f.text_field :description, placeholder: "Board description" %>
          </div>

          <div class="field color_field">
          	<%= f.label :color, class: 'color_label' %>
            <%= f.color_field :color %>
          </div>
          <div class="actions">
            <%= f.submit 'Submit board', :class => 'sidebar-buttons' %>
          </div>
        <% end %>
      </div>
      <div class = "edit-info">

      </div>
      <% else %>
	      <div class="add-info">
	      	<h4><%= link_to "Log in", login_path %> to add some boards!</h4>
	      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<% if !notice.blank?  %>
<p id="notice" class="alert alert-success"><%= notice %></p>
<%end%>
<div id = "board-sounds">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sounds-header" style = "background-color: <%= @board.color %>;">
      <h3><%= @board.name %></h3>
      <div class = "description">
        <p><%= @board.description %></p>
      </div>
    </div>
    <% if @board.sounds.count > 0 %>
      <%= will_paginate @sounds, :class => 'pagination first' %>
        <% @sounds.each do |sound| %>
          <%= render 'sound', sound: sound %>
        <% end %>
      <%= will_paginate @sounds %>
    <% else %>
      <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <p id = "empty-content-message">There doesn't seem to be anything here! Be first first to create a new sound on this board.</p>
      </div>
    <% end %>
  </div>
</div>

<div id = "board-info">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 board-info-container"> 	    
      <% if logged_in? %>
      <div class = "blank-info">
        <% @tags.each do |tag| %>
          <p class = "tag">#<%=tag.name %></p>
        <% end %>
      </div>
      <div class = "add-info">
        <h4>Submit a new sound</h4>
        <%= form_for([@board, @board.sounds.build]) do |f| %>
	  <%= f.hidden_field :user_id, value: current_user.id %>     
	  <div class="field">
            <%= f.text_field :name, placeholder: "Sound name" %>
          </div>
          <div class="field">
            <span id="fileError"></span>
            <%= f.file_field :soundAttachment, onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes } %>
          </div>
          <div class="actions">
            <%= f.submit 'Submit sound', :class => 'sidebar-buttons' %>
          </div>
        <% end %>
      </div>

      <div class = "tag-info">
        <h4>Submit a new tag</h4>
        <%= form_for([@board, @board.tags.build]) do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: "Tag name" %>
          </div>
           <div class="actions">
            <%= f.submit 'Submit tag', :class => 'sidebar-buttons' %>
          </div>
        <% end %>
      </div>

      <div class = "edit-info">
        <%= link_to 'Back to home', root_path, :class => 'sidebar-buttons back-button' %>
        <%= link_to 'Edit this board', edit_board_path(@board), :class => 'sidebar-buttons' %>
      </div>
    <% else %>
	<div class="tag-info">
		<h4><%=link_to "Log in", login_path %>  to add sounds!</h4>
		<%= link_to 'Back to home', root_path, :class => 'sidebar-buttons back-button' %>
 
	</div>
    <% end %>
    </div>
  </div>
</div>