config/routes.rb
Rails.application.routes.draw do
  resources :tags
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :boards do
    resources :tags 
    resources :sounds do 
	    resources :comments
    end
  end
  resources :users do
    resources :comments
  end
  resources :users do
    resources :sounds
  end
  root "boards#index"
end

app/models/sound.rb
class Sound < ApplicationRecord
   require 'file_size_validator' 
   mount_uploader :soundAttachment, SoundAttachmentUploader
   validates :name, presence: true
   validates :soundAttachment, presence: true #, :file_size => { :maximum => 10.megabytes.to_i } 
   validate :soundSizeValidation
   has_many :comments, dependent: :destroy
   belongs_to :board
   belongs_to :user
   private

   ## Validates whether or not the size of the SoundAttachment exceeds 5MB. If it does, the server should not upload it.
   def soundSizeValidation
	   puts "is over 5MB" if soundAttachment.size > 5.megabytes #TODO: Test console log to make sure this works
	   errors[:soundAttachment] << "should be less than 5MB" if soundAttachment.size > 5.megabytes
   end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]
  before_action :delete_from_s3, only: [:destroy]

  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
  end

  # GET /sounds/new
  def new
    @sound = Sound.new
  end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds
  # POST /sounds.json
  def create
    @board = Board.find(params[:board_id])
    @sound = @board.sounds.create(sound_params)
    redirect_to board_path(@board)
  end

  # PATCH/PUT /sounds/1
  # PATCH/PUT /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @board = Board.find(params[:board_id])
    @sound = Sound.find(params[:id])
    @sound.destroy

    respond_to do |format|
      format.html { redirect_to board_path(@board) }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
      @board = Board.find(params[:board_id])
      @comments = @sound.comments.paginate(:per_page => 10, :page => params[:page]).order("created_at DESC")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.require(:sound).permit(:name, :soundAttachment, :board_id, :user_id)
    end

    def delete_from_s3
      key = params[:soundAttachment].split('amazonaws.com/')[1]
      S3_BUCKET.object(key).delete
      return true
      rescue => e
        # Do nothing. Leave the now defunct file sitting in the bucket.
        return true
    end
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/sounds/_comment.html.erb
<div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sound-container">
  <div class = "container">
    <div class = "row">
      <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 right-content">
	<h5>
	  <% if comment.user_id %>
	    <%= gravatar_for User.find(comment.user_id), size: 25 %>
	    <%= link_to User.find(comment.user_id).name, User.find(comment.user_id) %>
	  <% end %>
	</h5>
	<h4><%= comment.body %></h4>
	<p>Submitted <%= time_ago_in_words(comment.created_at) %> ago</p>
	<% if logged_in? && current_user.admin? && current_user.id?(comment.user_id) %>
      	<%= link_to 'Delete', board_sound_comment_path(@board, @sound, comment), data: { confirm: 'Are you sure?' }, method: :delete %>
      	<%end%>
      </div>
    </div>
  </div>
</div>

app/views/sounds/_form.html.erb
<div id = "board-info" class = "form">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 board-info-container">
      <div class = "blank-info"></div>
      <%= form_for([@board, @sound]) do |f| %>
        <% if !@sound.errors.empty? %>
          <div class = "alert alert-error">

            <ul>
              <% @sound.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>

          </div>
        <% end %>

        <div class = "add-info">
          <div class="field">
            <%= f.text_field :name, placeholder: "Board name" %>
          </div>

          <div class="field">
            <%= f.file_field :soundAttachment %>
          </div>

          <div class="actions">
            <%= f.submit 'Submit board', :class => 'sidebar-buttons' %>
          </div>
        </div>

        <div class = "edit-info">
          <%= link_to 'Show this board', board_sound_path(@board, @sound), :class => 'sidebar-buttons back-button' %>
          <%= link_to 'Back to home', boards_path(@board), :class => 'sidebar-buttons' %>
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/sounds/edit.html.erb
<%= render 'form', sound: @sound %>

app/views/sounds/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New sound", new_sound_path, class: "btn btn-primary" %>

<table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @sounds.each do |sound| %>
         
         <tr>
            <td><%= sound.name %></td>
            <td><%= link_to "Download sound", sound.soundAttachment_url %></td>
            <td><%= button_to "Delete",  sound, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{sound.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/sounds/new.html.erb
<%= render 'form', sound: @sound %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<div id = "board-sounds">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 sounds-header">
      <h3><%= @sound.name %></h3>
      <div class = "description">
        <i class = "fa fa-play-circle-o" id = "sound-play-pause-<%= @sound.id %>" aria-hidden = "true" onClick="handleAudioImageClick('<%= @sound.id %>')"></i>
        <audio loop id = "<%= @sound.id %>-audio">
          <source src = "<%= @sound.soundAttachment.url %>" type = "audio/mp3">
        </audio>
      </div>
    </div>
    <% if @comments.count > 0 %>
      <%= will_paginate @comments, :class => 'pagination first' %>
        <% @comments.each do |comment| %>
          <%= render 'comment', comment: comment %> 
        <% end %>
      <%= will_paginate @comments %>
    <% else %>
      <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <p id = "empty-content-message">There doesn't seem to be anything here! Be first to comment on this sound.</p>
      </div>
    <% end %>
  </div>
</div>

<div id = "board-info">
  <div class = "row">
    <div class = "col-lg-12 col-md-12 col-sm-12 col-xs-12 board-info-container">
      <%if logged_in?%>
      <div class = "blank-info"></div>
      <div class = "add-info">
	<h4>Submit a new comment</h4>

	<%= form_for([@board, @sound, @sound.comments.build]) do |f| %>
	  <%= f.hidden_field :user_id, value: current_user.id %>
          <div class="field">
            <%= f.text_area :body, placeholder: "Comment" %>
          </div>
          <div class="actions">
            <%= f.submit 'Submit comment', :class => 'sidebar-buttons' %>
          </div>
  	<% end %>
      </div>
      <div class = "edit-info">
        <%= link_to 'Back to board', board_path(@board), :class => 'sidebar-buttons back-button' %>
        <%= link_to 'Edit this sound', edit_board_sound_path(@board, @sound), :class => 'sidebar-buttons' %>
      </div>
	<% else %>
		<div class="add-info">
			<h4><%= link_to "Log in", login_path %> to post a comment!</h4>
 			<%= link_to 'Back to board', board_path(@board), :class => 'sidebar-buttons back-button' %>
 
		</div>
	<%end%>
    </div>
  </div>
</div>