config/routes.rb
Rails.application.routes.draw do
  resources :tags
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :boards do
    resources :tags 
    resources :sounds do 
	    resources :comments
    end
  end
  resources :users do
    resources :comments
  end
  resources :users do
    resources :sounds
  end
  root "boards#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundShare</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <h1 class = "navbar-brand">SoundShare</h1>
          <!--%= link_to 'Mpgur', boards_path, class: "navbar-brand" %-->
        </div>

        <ul class = "nav navbar-nav navbar-left">
          <li><%= link_to boards_path, id: "home-link" do %><i class="fa fa-home" aria-hidden="true"></i><% end %></li>
        </ul>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
              <li><%= link_to 'Sign up', new_user_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div id = "main-header"></div>
  	<div id = "main-content" class = "container">
  	  <%= yield %>
    </div>
  </body>
</html>